name: Generate Static

on:
  push:
    branches:
      - main

jobs:
  generate:
    name: Generate
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Generate static
      run: python3 generate_static.py

    - name: Commit report
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "Generate static files"
        git push
